apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: devops-project
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: devops-project
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
   

spec:
  ingressClassName: alb
  # tls:
  # - hosts: 
    # - app.com
    # - grafana.app.com
    # secretName: app-tls-secret
        
  rules:
  - host: app.local
    http:
      paths:

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 8080

      - path: /health
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 8080 

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80
      

  - host: grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana    
            port:
              number: 80
